name: MaskFS Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux32:
    name: Build Linux x32
    runs-on: ubuntu-latest
    env:
      TARGET: i686-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_gm_maskfs_linux.dll
        path: target/release/libgm_maskfs.so

  build-linux64:
    name: Build Linux x64
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_gm_maskfs_linux64.dll
        path: target/release/libgm_maskfs.so

  build-win64:
    name: Build Windows x64
    runs-on: windows-latest
    env:
      TARGET: x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_gm_maskfs_win64.dll
        path: target/release/gm_maskfs.dll

  build-win32:
    name: Build Windows x32
    runs-on: windows-latest
    env:
      TARGET: i686-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
    - run: |
        rustup install nightly
        rustup default nightly
    - uses: actions-rs/toolchain@v1
      with:
        profile: default
        toolchain: nightly
    - run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: gmsv_gm_maskfs_win32.dll
        path: target/release/gm_maskfs.dll